current:
  - bias
  - current_word.lower()
  - current_word[-3]
  - current_word[-2]
  - current_word.isupper()
  - current_word.istitle()
  - current_word.isdigit()
  - current_word.islower()
  - current_postag
  - current_name
  - current_comp_suffix
  - current_com_single
  - current_city
  - current_country
  - current_tfidf
  - current_tfdf
previous:
  - previous_word.lower()
  - previous_word.istitle()
  - previous_word.isupper()
  - previous_postag
  - previous_name
  - previous_com_suffix
  - previous_com_single
  - previous_city
  - previous_country
  - previous_tfidf
  - previous_tfdf
next:
  - next_word.lower()
  - next_word.istitle()
  - next_word.isupper()
  - next_postag
  - next_name
  - next_com_suffix
  - next_com_single
  - next_city
  - next_country
  - next_tfidf
  - next_tfdf
previous2:
  - previous2_word.lower()
  - previous2_word.istitle()
  - previous2_word.isupper()
  - previous2_postag
  - previous2_name
  - previous2_com_suffix
  - previous2_com_single
  - previous2_city
  - previous2_country
  - previous2_tfidf
  - previous2_tfdf
next2:
  - next2_word.lower()
  - next2_word.istitle()
  - next2_word.isupper()
  - next2_postag
  - next2_name
  - next2_com_suffix
  - next2_com_single
  - next2_city
  - next2_country
  - next2_tfidf
  - next2_tfdf