current:
  - bias
  - current_word.lower()
  - current_word[-3]
  - current_word[-2]
  - current_word.isupper()
  - current_word.istitle()
  - current_word.isdigit()
  - current_word.islower()
  - current_postag
  - current_name
  - current_comp_suffix
  - current_com_single
  - current_city
  - current_country
  - current_product
  - current_event
  - current_tfidf
  - current_tfdf
previous:
  - previous_word.lower()
  - previous_word.istitle()
  - previous_word.isupper()
  - previous_postag
  - previous_name
  - previous_com_suffix
  - previous_com_single
  - previous_city
  - previous_country
  - previous_product
  - previous_event
  - previous_tfidf
  - previous_tfdf
next:
  - next_word.lower()
  - next_word.istitle()
  - next_word.isupper()
  - next_postag
  - next_name
  - next_com_suffix
  - next_com_single
  - next_city
  - next_country
  - next_product
  - next_event
  - next_tfidf
  - next_tfdf